app/models.py
from app import db
from app.utils import transpose, space, column_space, row_space, lattice, isomorphic
from sqlalchemy.orm import relationship


def intersection(r_class, l_class):
    join = set(r_class.h_classes()) & set(l_class.h_classes())
    return list(join)[0]


def width(h_class):
    return h_class.matrices[0].width


def height(h_class):
    return h_class.matrices[0].height


class Matrix(db.Model):
    __tablename__ = 'matrix'
    id = db.Column(db.Integer, primary_key=True)
    width = db.Column(db.Integer)
    height = db.Column(db.Integer)
    body = db.Column(db.Integer)
    h_class_id = db.Column(db.Integer, db.ForeignKey('h_class.id'))
    h_class = relationship('H_class', back_populates='matrices')
    l_class_id = db.Column(db.Integer, db.ForeignKey('l_class.id'))
    l_class = relationship('L_class', back_populates='matrices')
    r_class_id = db.Column(db.Integer, db.ForeignKey('r_class.id'))
    r_class = relationship('R_class', back_populates='matrices')
    d_class_id = db.Column(db.Integer, db.ForeignKey('d_class.id'))
    d_class = relationship('D_class', back_populates='matrices')

    __mapper_args__ = {
        "order_by": id
    }

    def to_array(self):
        data = [[]] * self.height
        for k in range(self.height):
            data[k] = [0] * self.width
        for i in range(self.height):
            for j in range(self.width):
                shift = self.width * self.height - (i * self.width + j) - 1
                if 1 << shift & self.body:
                    data[i][j] = 1
        return data

    def column_space(self):
        return column_space(self.to_array())

    def row_space(self):
        return row_space(self.to_array())

    def row_lattice(self):
        return lattice(list(self.row_space()))

    def __repr__(self):
        return '<Matrix {}x{}>'.format(self.width, self.height)


class H_class(db.Model):
    __tablename__ = 'h_class'
    id = db.Column(db.Integer, primary_key=True)
    matrices = relationship('Matrix', back_populates='h_class')

    __mapper_args__ = {
        "order_by": id
    }


class L_class(db.Model):
    __tablename__ = 'l_class'
    id = db.Column(db.Integer, primary_key=True)
    matrices = relationship('Matrix', back_populates='l_class')

    __mapper_args__ = {
        "order_by": id
    }

    def h_classes(self):
        return H_class.query.join(Matrix).join(L_class).filter_by(id=self.id).all()


class R_class(db.Model):
    __tablename__ = 'r_class'
    id = db.Column(db.Integer, primary_key=True)
    matrices = relationship('Matrix', back_populates='r_class')

    __mapper_args__ = {
        "order_by": id
    }

    def h_classes(self):
        return H_class.query.join(Matrix).join(R_class).filter_by(id=self.id).all()


class D_class(db.Model):
    __tablename__ = 'd_class'
    id = db.Column(db.Integer, primary_key=True)
    matrices = relationship('Matrix', back_populates='d_class')

    __mapper_args__ = {
        "order_by": id
    }

    def h_classes(self):
        return H_class.query.join(Matrix).join(D_class).filter_by(id=self.id).all()

    def l_classes(self):
        return L_class.query.join(Matrix).join(D_class).filter_by(id=self.id).all()

    def r_classes(self):
        return R_class.query.join(Matrix).join(D_class).filter_by(id=self.id).all()

app/__init__.py
import click
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)
    app.config['BOOTSTRAP_SERVE_LOCAL'] = True

    db.init_app(app)
    migrate.init_app(app, db)
    bootstrap.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    @app.cli.command('init')
    @click.option('--height', default=3, help='Maximum matix height.')
    @click.option('--width', default=3, help='Maximum matrix width.')
    def init(height, width):
        """ Initialize matrices and classes """
        from app.tasks import init

        time = init(int(height), int(width))

        print(f'Estimated time: {time} seconds.')

    return app

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import base64
import networkx as nx
import matplotlib

matplotlib.use('Agg')

import matplotlib.pyplot as plt

from io import BytesIO
from app import db
from app.main import bp
from app.models import Matrix, intersection, width, height
from flask import render_template, request, url_for, current_app, send_file
from importlib import import_module
from app.tasks import app
from matplotlib.figure import Figure

app.app_context().push()


@bp.route('/')
def index():
    return render_template('index.html', title='Home')


@bp.route('/theory')
def theory():
    return render_template('theory.html', title='Theory')


@bp.route('/matrix')
def matrix_index():
    page = request.args.get('page', 1, type=int)
    matrices = Matrix.query.paginate(
        page, current_app.config['MATRICES_PER_PAGE'], False
    )
    next_url = url_for('main.matrix_index', page=matrices.next_num) \
        if matrices.has_next else None
    prev_url = url_for('main.matrix_index', page=matrices.prev_num) \
        if matrices.has_prev else None
    return render_template('matrix/index.html', title='Matrices', matrices=matrices.items,
                           page=matrices.page, pages=matrices.pages, per_page=matrices.per_page, total=matrices.total,
                           next_url=next_url, prev_url=prev_url)


@bp.route('/poset')
def poset():
    G = nx.complete_graph(5)
    nx.draw(G)

    img = BytesIO() # file-like object for the image
    plt.savefig(img, format='png') # save the image to the stream
    plt.clf()

    data = base64.b64encode(img.getbuffer()).decode("ascii")
    return render_template('poset.html', title='Partial order set of D-classes', data=data)


@bp.route('/explore/<string:class_name>')
def explore_index(class_name):
    from app.models import D_class

    d_classes = D_class.query.all()
    return render_template('explore/index.html', title=class_name+'-classes',
                           d_classes=d_classes, intersection=intersection, class_name=class_name,
                           height=height, width=width)


@bp.route('/explore/<string:class_name>/<int:class_id>')
def explore_show(class_name, class_id):
    width = int(request.args.get('width'))
    height = int(request.args.get('height'))
    size = int(request.args.get('size'))

    model = getattr(import_module('app.models'), class_name+'_class')

    matrices = model.query.get(class_id).matrices

    return render_template('explore/show.html', matrices=matrices, width=width, height=height, size=size)


@bp.route('/class/<string:class_name>/<int:class_id>')
def class_show(class_name, class_id):
    model = getattr(import_module('app.models'), class_name+'_class')

    page = request.args.get('page', 1, type=int)
    matrices = db.session.query(Matrix).join(model).filter(model.id == class_id).paginate(
        page, current_app.config['MATRICES_PER_PAGE'], False
    )
    next_url = url_for('main.class_show', class_name=class_name, class_id=class_id, page=matrices.next_num) \
        if matrices.has_next else None
    prev_url = url_for('main.class_show', class_name=class_name, class_id=class_id, page=matrices.prev_num) \
        if matrices.has_prev else None

    return render_template('class/show.html', class_name=class_name, matrices=matrices.items,
                           page=matrices.page, pages=matrices.pages, per_page=matrices.per_page, total=matrices.total,
                           next_url=next_url, prev_url=prev_url)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - Boolean Matrices{% else %}Boolean Matrices{% endif %}
{% endblock %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapse" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toogle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Boolean Matrices</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('main.theory') }}">Theory</a></li>
                    <li><a href="{{ url_for('main.matrix_index') }}">Matrices</a></li>
                    <li><a href="{{ url_for('main.explore_index', class_name='H') }}">H-classes</a></li>
                    <li><a href="{{ url_for('main.explore_index', class_name='L') }}">L-classes</a></li>
                    <li><a href="{{ url_for('main.explore_index', class_name='R') }}">R-classes</a></li>
                    <li><a href="{{ url_for('main.explore_index', class_name='D') }}">D-classes</a></li>
                    <li><a href="{{ url_for('main.poset') }}">Partial order of D-classes</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript" id="MathJax-script" async
            src="{{ url_for('static', filename='MathJax/es5/tex-chtml-full.js') }}">
    </script>
    <script>
        MathJax = {
          tex: {
            inlineMath: [['$', '$']]
          }
        };
    </script>
    <script type="text/javascript" src="{{ url_for('static',
                  filename='script.js') }}"></script>
{% endblock %}

app/templates/class/h_class.html
<table>
    <tr>
    {% for matrix in matrices %}
        <td>
            {% set array = matrix.to_array() %}
            $$\begin{Vmatrix}{% for column in range(array|length - 1)        %}
                             {%     for row in range(array[0]|length - 1)    %}
                             {{         array[column][row]                  }}&
                             {%     endfor                                   %}
                             {{     array[column][array[0]|length - 1]     }}\\
                             {% endfor                                       %}
                             {% for row in range(array[0]|length - 1)        %}
                             {{     array[array|length - 1][row]            }}&
                             {% endfor                                       %}
                             {{ array[array|length - 1][array[0]|length - 1] }}\end{Vmatrix}$$
        </td>
    {% endfor %}
    </tr>
</table>

app/templates/class/show.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Matrices</h1>
    <table style="width: 100%;">
        {% for i in range(5) %}
        <tr>
        {% for j in range(5) %}
            <td>
                {% if (page - 1) * per_page + 5 * i + j < total %}
                    {% set array = matrices[5*i+j].to_array() %}
                    $$\begin{Vmatrix}{% for column in range(array|length - 1)        %}
                                     {%     for row in range(array[0]|length - 1)    %}
                                     {{         array[column][row]                  }}&
                                     {%     endfor                                   %}
                                     {{     array[column][array[0]|length - 1]     }}\\
                                     {% endfor                                       %}
                                     {% for row in range(array[0]|length - 1)        %}
                                     {{     array[array|length - 1][row]            }}&
                                     {% endfor                                       %}
                                     {{ array[array|length - 1][array[0]|length - 1] }}\end{Vmatrix}$$
                {% endif %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </table>
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Previous
                </a>
            </li>
            <li>
                {{ page }}/{{ pages }}
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/classes.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Classes</h1>
    {% for matrix in matrices %}
        {% include '_class.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Previous
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/explore/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>{{class_name}}-classes</h1>
    <!-- The Modal -->
    <div id="myModal" class="modal">
        <!-- Modal content -->
    </div>
    <table style="width: 100%; text-align: center;">
    {% set offset = namespace(value=0, step=0) %}
    {% for d_class in d_classes %}
        {% if class_name == 'H' %}
            {% set offset.step=d_class.r_classes()|length %}
            {% set l_classes = d_class.l_classes() %}
            {% set r_classes = d_class.r_classes() %}
        {% elif class_name == 'L' %}
            {% set offset.step=1 %}
            {% set l_classes = d_class.l_classes() %}
            {% set r_classes = range(1) %}
        {% elif class_name == 'R' %}
            {% set offset.step=d_class.r_classes()|length %}
            {% set l_classes = range(1) %}
            {% set r_classes = d_class.r_classes() %}
        {% elif class_name == 'D' %}
            {% set offset.step=1 %}
            {% set l_classes = range(1) %}
            {% set r_classes = range(1) %}
        {% endif %}
        {% for l_class in l_classes %}
        <tr>
            {% for i in range(offset.value) %}
            <td>
            </td>
            {% endfor %}
            {% for r_class in r_classes %}
            {% if class_name == 'H' %}
                {% set class = intersection(l_class, r_class) %} 
            {% elif class_name == 'L' %}
                {% set class = l_class %} 
            {% elif class_name == 'R' %}
                {% set class = r_class %} 
            {% elif class_name == 'D' %}
                {% set class = d_class %} 
            {% endif %}
            <td onmouseenter="class_show('{{class_name}}', {{class.id}}, {{class.matrices|length}})"
                onmouseleave="class_hide()" style="border: 1px solid;">
                <a href="{{ url_for('main.class_show', class_name=class_name,
                    class_id=class.id) }}">
                    {{ class.matrices|length }}
                </a>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
        {% set offset.value = offset.value + offset.step %}
    {% endfor %}
    </table>
{% endblock %}

app/templates/explore/show.html
<table style="width: 100%; height: 100%;">
    {% for i in range(height) %}
    <tr>
    {% for j in range(width) %}
        {% if width * i + j < size  %}
        <td>
            {% set array = matrices[width * i + j].to_array() %}
            $$\begin{Vmatrix}{% for column in range(array|length - 1)        %}
                             {%     for row in range(array[0]|length - 1)    %}
                             {{         array[column][row]                  }}&
                             {%     endfor                                   %}
                             {{     array[column][array[0]|length - 1]     }}\\
                             {% endfor                                       %}
                             {% for row in range(array[0]|length - 1)        %}
                             {{     array[array|length - 1][row]            }}&
                             {% endfor                                       %}
                             {{ array[array|length - 1][array[0]|length - 1] }}\end{Vmatrix}$$
        </td>
        {% else %}
        <td></td>
        {% endif %}
    {% endfor %}
    </tr>
    {% endfor %}
</table>

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Boolean Matrices</h1>
{% endblock %}

app/templates/matrices.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Matrices</h1>
    <table style="width: 100%;">
        {% for i in range(4) %}
        <tr>
        {% for j in range(5) %}
            <td>
                {% if (page - 1) * per_page + 5 * i + j < total %}
                    {% set array = matrices[5*i+j].to_array() %}
                    {% include '_matrix.html' %}
                {% endif %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </table>
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Previous
                </a>
            </li>
            <li>
                {{ page }}/{{ pages }}
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/matrix/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Matrices</h1>
    <table style="width: 100%;">
        {% for i in range(5) %}
        <tr>
        {% for j in range(5) %}
            <td>
                {% if (page - 1) * per_page + 5 * i + j < total %}
                    {% set array = matrices[5*i+j].to_array() %}
                    $$\begin{Vmatrix}{% for column in range(array|length - 1)        %}
                                     {%     for row in range(array[0]|length - 1)    %}
                                     {{         array[column][row]                  }}&
                                     {%     endfor                                   %}
                                     {{     array[column][array[0]|length - 1]     }}\\
                                     {% endfor                                       %}
                                     {% for row in range(array[0]|length - 1)        %}
                                     {{     array[array|length - 1][row]            }}&
                                     {% endfor                                       %}
                                     {{ array[array|length - 1][array[0]|length - 1] }}\end{Vmatrix}$$
                {% endif %}
            </td>
        {% endfor %}
        </tr>
    {% endfor %}
    </table>
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Previous
                </a>
            </li>
            <li>
                {{ page }}/{{ pages }}
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}

app/templates/poset.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Partial order set of D-classes</h1>
    <img src='data:image/png;base64,{{data}}'/>
{% endblock %}

app/templates/r_classes.html
{% extends "base.html" %}

{% block app_content %}
    <h1>R classes</h1>
    {% for r_class in r_classes %}
        {% include '_r_class.html' %}
    {% endfor %}
    <nav aria-label="...">
        <ul class="pager">
            <li class="previous{% if not prev_url %} disabled{% endif %}">
                <a href="{{ prev_url or '#' }}">
                    <span aria-hidden="true">&larr;</span> Previous
                </a>
            </li>
            <li class="next{% if not next_url %} disabled{% endif %}">
                <a href="{{ next_url or '#' }}">
                    Next <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}